title: Title of your CV site
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "OKWHAROBO, Solomon Monday"
job: "Mobile Developer || Mathematician"

phone_number: +2349-1676-38610
address: Lagos, Nigeria
email: mondaysolomon01@gmail.com
linkedin_username: okwharobSM
github_username: black-coda
instagram_username: __iammonday
twitter_username: SOkwharobo
facebook_username: facebook
youtube_username: youtube
blog_url: https://dev.to/blackcoda/

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag